#import <PEGKit/PKParser.h>

enum {
    DLWPARSER_TOKEN_KIND_A = 14,
    DLWPARSER_TOKEN_KIND_SAVE = 15,
    DLWPARSER_TOKEN_KIND_ADD = 16,
    DLWPARSER_TOKEN_KIND_B = 17,
    DLWPARSER_TOKEN_KIND_POUND = 18,
    DLWPARSER_TOKEN_KIND_SEMI_COLON = 19,
    DLWPARSER_TOKEN_KIND_COMMA = 20,
    DLWPARSER_TOKEN_KIND_C = 21,
    DLWPARSER_TOKEN_KIND_JUMP = 22,
    DLWPARSER_TOKEN_KIND_D = 23,
    DLWPARSER_TOKEN_KIND_PLUS = 24,
    DLWPARSER_TOKEN_KIND_JUMPN = 25,
    DLWPARSER_TOKEN_KIND_SUB = 26,
    DLWPARSER_TOKEN_KIND_LOAD = 27,
    DLWPARSER_TOKEN_KIND_JUMPZ = 28,
    DLWPARSER_TOKEN_KIND_OPEN_PAREN = 29,
    DLWPARSER_TOKEN_KIND_CLOSE_PAREN = 30,
    DLWPARSER_TOKEN_KIND_JUMPO = 31,
};

@interface DLWParser : PKParser

@end

